#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import re

 def check_password_strength(password):
     # Criteria for strength
     length_criteria = len(password) >=8
     uppercase_criteria = bool(re.search(r'[A-Z]', password))
     lowercase_criteria = bool(re.search(r'[a-z]', password))
     number_criteria = bool(re.search(r'\d', password))
     special_char_criteria = bool(re.search(r'[!@#$%^&*(),.?":{}|<>]', password))

     # Count satisfied criteria
     score = sum([length_criteria, uppercase_criteria, lowercase_criteria, number_criteria, special_char_criteria])

     if score == 5:
         return "Strong"
     elif score >= 3:
         return "Moderate"
     else:
